spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    #https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false