apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jaipro-resource-server
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jaipro-resource-server
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 150
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 500