apiVersion: v1
kind: Service
metadata:
  name: personal-finance-management
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 31234
  selector:
    service: personal-finance-management
    type: backend